ccert/ecert scripts
Renames the `ccert` script to `ecert`, as it displays expiration data.
The new `ccert` script compares key/cert checksums to see if they match.

diff --git a/scripts/.local/bin/ccert b/scripts/.local/bin/ccert
--- a/scripts/.local/bin/ccert
+++ b/scripts/.local/bin/ccert
@@ -1,24 +1,23 @@
 #!/usr/bin/env bash
 
-if [ -z "$1" ]
-then
-	echo "domain name missing"
+if [ -z "$1" ]; then
+	echo "key path missing"
 	exit 1
 fi
-name="$1"
-shift
 
-now_epoch=$( date +%s )
-output=""
-index=2
-ips=$(dig +noall +answer "$name" | awk '{print $5}')
+if [ -z "$2" ]; then
+	echo "cert path missing"
+	exit 1
+fi
 
-for ip in $ips; do
-	expiry_date=$( echo | openssl s_client -showcerts -servername "$name" -connect "$ip:443" 2>/dev/null | openssl x509 -inform pem -noout -enddate | cut -d "=" -f 2 )
-	expiry_epoch=$( date -d "$expiry_date" +%s )
-	expiry_days="$(( (expiry_epoch - now_epoch) / (3600 * 24) ))"
-	output+="\e[3${index}m$ip\e[0m|$expiry_date|$expiry_days days\n"
-	((index=index+1))
-done
+keyChecksum=$(openssl pkey -in $1 -pubout -outform pem | sha256sum)
+certChecksum=$(openssl x509 -in $2 -pubkey -noout -outform pem | sha256sum)
 
-echo -e "$output" | column -t -s "|"
+if [[ "$keyChecksum" == "$certChecksum" ]]; then
+	echo "key/cert checksums match!"
+else
+	echo "key/cert checksums DO NOT match!"
+fi
+
+echo "key:  $keyChecksum"
+echo "cert: $certChecksum"
